$ airtest run 81n炸狗v4.0.air --device Android://127.0.0.1:5037/127.0.0.1:7555
do not save log
[04:33:31][DEBUG]<airtest.core.android.adb> c:\users\maple\.virtualenvs\airtest-
fkwpavgu\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 50
37 -s 127.0.0.1:7555 get-state
[04:33:31][DEBUG]<airtest.core.android.adb> c:\users\maple\.virtualenvs\airtest-
fkwpavgu\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 50
37 -s 127.0.0.1:7555 wait-for-device
[04:33:32][DEBUG]<airtest.core.android.adb> c:\users\maple\.virtualenvs\airtest-
fkwpavgu\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 50
37 -s 127.0.0.1:7555 shell getprop ro.build.version.sdk
Traceback (most recent call last):
  File "F:\AirTest\81n炸狗v4.0.air\81n炸狗v4.0.py", line 447, in run_case_again
    func(*args, **keyargs)
  File "F:\AirTest\81n炸狗v4.0.air\81n炸狗v4.0.py", line 524, in bomb_dog
    nav_back()
  File "F:\AirTest\81n炸狗v4.0.air\81n炸狗v4.0.py", line 64, in nav_back
    nav_back()
  File "F:\AirTest\81n炸狗v4.0.air\81n炸狗v4.0.py", line 62, in nav_back
    touch(Template(r"tpl1612973584765.png", target_pos=4, record_pos=(-0.369, -0
.24), resolution=(1440, 810)))
  File "c:\users\maple\.virtualenvs\airtest-fkwpavgu\lib\site-packages\airtest\u
tils\logwraper.py", line 90, in wrapper
    res = f(*args, **kwargs)
  File "c:\users\maple\.virtualenvs\airtest-fkwpavgu\lib\site-packages\airtest\c
ore\api.py", line 352, in touch
    pos = loop_find(v, timeout=ST.FIND_TIMEOUT)
  File "c:\users\maple\.virtualenvs\airtest-fkwpavgu\lib\site-packages\airtest\u
tils\logwraper.py", line 90, in wrapper
    res = f(*args, **kwargs)
  File "c:\users\maple\.virtualenvs\airtest-fkwpavgu\lib\site-packages\airtest\c
ore\cv.py", line 66, in loop_find
    match_pos = query.match_in(screen)
  File "c:\users\maple\.virtualenvs\airtest-fkwpavgu\lib\site-packages\airtest\c
ore\cv.py", line 145, in match_in
    match_result = self._cv_match(screen)
  File "c:\users\maple\.virtualenvs\airtest-fkwpavgu\lib\site-packages\airtest\u
tils\logwraper.py", line 90, in wrapper
    res = f(*args, **kwargs)
  File "c:\users\maple\.virtualenvs\airtest-fkwpavgu\lib\site-packages\airtest\c
ore\cv.py", line 169, in _cv_match
    ret = self._try_match(func, image, screen, threshold=self.threshold, rgb=sel
f.rgb)
  File "c:\users\maple\.virtualenvs\airtest-fkwpavgu\lib\site-packages\airtest\c
ore\cv.py", line 178, in _try_match
    ret = func(*args, **kwargs).find_best_result()
  File "c:\users\maple\.virtualenvs\airtest-fkwpavgu\lib\site-packages\airtest\a
ircv\keypoint_base.py", line 23, in wrapper
    ret = func(self, *args, **kwargs)
  File "c:\users\maple\.virtualenvs\airtest-fkwpavgu\lib\site-packages\airtest\a
ircv\keypoint_base.py", line 65, in find_best_result
    self.kp_sch, self.kp_src, self.good = self._get_key_points()
  File "c:\users\maple\.virtualenvs\airtest-fkwpavgu\lib\site-packages\airtest\a
ircv\keypoint_base.py", line 150, in _get_key_points
    kp_src, des_src = self.get_keypoints_and_descriptors(self.im_source)
  File "c:\users\maple\.virtualenvs\airtest-fkwpavgu\lib\site-packages\airtest\a
ircv\keypoint_matching_contrib.py", line 132, in get_keypoints_and_descriptors
    keypoints, descriptors = self.detector.detectAndCompute(image, None)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "f:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "f:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\maple\.virtualenvs\AirTest-fKWpAVgu\Scripts\airtest.exe\__main_
_.py", line 7, in <module>
  File "c:\users\maple\.virtualenvs\airtest-fkwpavgu\lib\site-packages\airtest\c
li\__main__.py", line 16, in main
    run_script(args)
  File "c:\users\maple\.virtualenvs\airtest-fkwpavgu\lib\site-packages\airtest\c
li\runner.py", line 155, in run_script
    result = unittest.TextTestRunner(verbosity=0).run(suite)
  File "f:\anaconda3\lib\unittest\runner.py", line 176, in run
    test(result)
  File "f:\anaconda3\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "f:\anaconda3\lib\unittest\suite.py", line 122, in run
    test(result)
  File "f:\anaconda3\lib\unittest\case.py", line 676, in __call__
    return self.run(*args, **kwds)
  File "f:\anaconda3\lib\unittest\case.py", line 628, in run
    testMethod()
  File "c:\users\maple\.virtualenvs\airtest-fkwpavgu\lib\site-packages\airtest\c
li\runner.py", line 70, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "F:\AirTest\81n炸狗v4.0.air\81n炸狗v4.0.py", line 555, in <module>
    bomb_dog()
  File "F:\AirTest\81n炸狗v4.0.air\81n炸狗v4.0.py", line 449, in run_case_again
    close_and_start()
  File "F:\AirTest\81n炸狗v4.0.air\81n炸狗v4.0.py", line 303, in close_and_start

    sleep(2)
  File "c:\users\maple\.virtualenvs\airtest-fkwpavgu\lib\site-packages\airtest\u
tils\logwraper.py", line 90, in wrapper
    res = f(*args, **kwargs)
  File "c:\users\maple\.virtualenvs\airtest-fkwpavgu\lib\site-packages\airtest\c
ore\api.py", line 562, in sleep
    time.sleep(secs)
KeyboardInterrupt





















[10:10:24][ERROR]<airtest.core.api> Traceback (most recent call last):
  File "F:\AirTest\81n炸狗v4.0.air\81n炸狗v4.0.py", line 447, in run_case_again
    func(*args, **keyargs)
  File "F:\AirTest\81n炸狗v4.0.air\81n炸狗v4.0.py", line 514, in bomb_dog
    wait(Template(r"tpl1613989550759.png", record_pos=(0.046, 0.016), resolution
=(1440, 810)), timeout=50)
  File "c:\users\maple\.virtualenvs\airtest-fkwpavgu\lib\site-packages\airtest\u
tils\logwraper.py", line 90, in wrapper
    res = f(*args, **kwargs)
  File "c:\users\maple\.virtualenvs\airtest-fkwpavgu\lib\site-packages\airtest\c
ore\api.py", line 591, in wait
    pos = loop_find(v, timeout=timeout, interval=interval, intervalfunc=interval
func)
  File "c:\users\maple\.virtualenvs\airtest-fkwpavgu\lib\site-packages\airtest\u
tils\logwraper.py", line 90, in wrapper
    res = f(*args, **kwargs)
  File "c:\users\maple\.virtualenvs\airtest-fkwpavgu\lib\site-packages\airtest\c
ore\cv.py", line 77, in loop_find
    raise TargetNotFoundError('Picture %s not found in screen' % query)
airtest.core.error.TargetNotFoundError: 'Picture Template(81n炸狗v4.0.air\\tpl16
13989550759.png) not found in screen'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\maple\.virtualenvs\airtest-fkwpavgu\lib\site-packages\airtest\c
li\runner.py", line 70, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "F:\AirTest\81n炸狗v4.0.air\81n炸狗v4.0.py", line 555, in <module>
    bomb_dog()
  File "F:\AirTest\81n炸狗v4.0.air\81n炸狗v4.0.py", line 449, in run_case_again
    close_and_start()
  File "F:\AirTest\81n炸狗v4.0.air\81n炸狗v4.0.py", line 307, in close_and_start

    end_fight()
  File "F:\AirTest\81n炸狗v4.0.air\81n炸狗v4.0.py", line 55, in end_fight
    wait(Template(r"tpl1613057829277.png", record_pos=(0.12, 0.104), resolution=
(1440, 810)))
  File "c:\users\maple\.virtualenvs\airtest-fkwpavgu\lib\site-packages\airtest\u
tils\logwraper.py", line 90, in wrapper
    res = f(*args, **kwargs)
  File "c:\users\maple\.virtualenvs\airtest-fkwpavgu\lib\site-packages\airtest\c
ore\api.py", line 591, in wait
    pos = loop_find(v, timeout=timeout, interval=interval, intervalfunc=interval
func)
  File "c:\users\maple\.virtualenvs\airtest-fkwpavgu\lib\site-packages\airtest\u
tils\logwraper.py", line 90, in wrapper
    res = f(*args, **kwargs)
  File "c:\users\maple\.virtualenvs\airtest-fkwpavgu\lib\site-packages\airtest\c
ore\cv.py", line 77, in loop_find
    raise TargetNotFoundError('Picture %s not found in screen' % query)
airtest.core.error.TargetNotFoundError: 'Picture Template(81n炸狗v4.0.air\\tpl16
13057829277.png) not found in screen'

======================================================================
ERROR: runTest (airtest.cli.runner.AirtestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "F:\AirTest\81n炸狗v4.0.air\81n炸狗v4.0.py", line 447, in run_case_again
    func(*args, **keyargs)
  File "F:\AirTest\81n炸狗v4.0.air\81n炸狗v4.0.py", line 514, in bomb_dog
    wait(Template(r"tpl1613989550759.png", record_pos=(0.046, 0.016), resolution
=(1440, 810)), timeout=50)
  File "c:\users\maple\.virtualenvs\airtest-fkwpavgu\lib\site-packages\airtest\u
tils\logwraper.py", line 90, in wrapper
    res = f(*args, **kwargs)
  File "c:\users\maple\.virtualenvs\airtest-fkwpavgu\lib\site-packages\airtest\c
ore\api.py", line 591, in wait
    pos = loop_find(v, timeout=timeout, interval=interval, intervalfunc=interval
func)
  File "c:\users\maple\.virtualenvs\airtest-fkwpavgu\lib\site-packages\airtest\u
tils\logwraper.py", line 90, in wrapper
    res = f(*args, **kwargs)
  File "c:\users\maple\.virtualenvs\airtest-fkwpavgu\lib\site-packages\airtest\c
ore\cv.py", line 77, in loop_find
    raise TargetNotFoundError('Picture %s not found in screen' % query)
airtest.core.error.TargetNotFoundError: 'Picture Template(81n炸狗v4.0.air\\tpl16
13989550759.png) not found in screen'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\maple\.virtualenvs\airtest-fkwpavgu\lib\site-packages\airtest\c
li\runner.py", line 73, in runTest
    six.reraise(*sys.exc_info())
  File "c:\users\maple\.virtualenvs\airtest-fkwpavgu\lib\site-packages\six.py",
line 703, in reraise
    raise value
  File "c:\users\maple\.virtualenvs\airtest-fkwpavgu\lib\site-packages\airtest\c
li\runner.py", line 70, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "F:\AirTest\81n炸狗v4.0.air\81n炸狗v4.0.py", line 555, in <module>
    bomb_dog()
  File "F:\AirTest\81n炸狗v4.0.air\81n炸狗v4.0.py", line 449, in run_case_again
    close_and_start()
  File "F:\AirTest\81n炸狗v4.0.air\81n炸狗v4.0.py", line 307, in close_and_start

    end_fight()
  File "F:\AirTest\81n炸狗v4.0.air\81n炸狗v4.0.py", line 55, in end_fight
    wait(Template(r"tpl1613057829277.png", record_pos=(0.12, 0.104), resolution=
(1440, 810)))
  File "c:\users\maple\.virtualenvs\airtest-fkwpavgu\lib\site-packages\airtest\u
tils\logwraper.py", line 90, in wrapper
    res = f(*args, **kwargs)
  File "c:\users\maple\.virtualenvs\airtest-fkwpavgu\lib\site-packages\airtest\c
ore\api.py", line 591, in wait
    pos = loop_find(v, timeout=timeout, interval=interval, intervalfunc=interval
func)
  File "c:\users\maple\.virtualenvs\airtest-fkwpavgu\lib\site-packages\airtest\u
tils\logwraper.py", line 90, in wrapper
    res = f(*args, **kwargs)
  File "c:\users\maple\.virtualenvs\airtest-fkwpavgu\lib\site-packages\airtest\c
ore\cv.py", line 77, in loop_find
    raise TargetNotFoundError('Picture %s not found in screen' % query)
airtest.core.error.TargetNotFoundError: 'Picture Template(81n炸狗v4.0.air\\tpl16
13057829277.png) not found in screen'

----------------------------------------------------------------------
Ran 1 test in 1465.031s

FAILED (errors=1)
